name: NoPhantoms
main: com.Melvin3000.NoPhantoms.NoPhantoms
version: 1.0
api-version: 1.15
commands:
    phantoms:
        description: Toggle if phantoms spawn for you
        usage: /<command>